### ISSUE TITLE
Customise gas for contract deployment

### ISSUE THREAD

**Issue by rolandsaven** [usecannon/cannon#243]
Hey there,

I've been playing around with cannon and trying to build a deployment process, but I'm having trouble customizing the gas values for contract deployment. I'm getting the following error while trying to deploy to Polygon Mainnet. (Deployment to Mumbai worked just fine.)

```json
{
 "code": -32000, 
 "message": "transaction underpriced"
}
```

Regarding reproduction, I tried deploying Synthetix's Oracle manager contract set, but it didn't work. 
https://github.com/Synthetixio/synthetix-v3/blob/main/protocol/oracle-manager/cannonfile.toml 

So if I try to build these contracts on Polygon Mainnet, it fails (Mumbai works).

I've been looking through Cannon's code and see that it's possible to define overrides. 
https://github.com/usecannon/cannon/blob/821b1abddd18232c5c4a84461823a53efb77d296/packages/builder/src/steps/contract.ts#L39-L44

I imagined the following would work, but it does not recognise the values. Am I doing something wrong?

```toml
[contract.InitialProxy]
artifact = "contracts/Proxy.sol:Proxy"
args = ["<%= contracts.CoreModule.address %>", "<%= settings.owner %>"]
salt = "<%= settings.salt %>"
abiOf = ["CoreModule"]
create2 = true
overrides.gasPrice = "150500000000"
overrides.priorityGasPrice = "40000000000"
```
