### ISSUE TITLE
Parsing / string interpolation in defaultValues for settings

### ISSUE THREAD

**Issue by noahlitvin** [usecannon/cannon#262]
Can we have it parse `defaultValue` ?

e.g. a user wants:
```toml
[setting.perpsMaxSnxEth]
defaultValue = "<%= MaxUint256 %>"
```
